Close streams on Windows to avoid locking issue when winding down JenkinsRulee
When JenkinsRule kicks in, it tries to cleanup temporary directories.
Using a logging file, this fails on Windows because the file
is still not closed.

```
Error
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
Stacktrace
java.lang.IllegalStateException: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
at io.jenkins.plugins.essentials.logging.EssentialsLoggingConfigurerTest.lambda$leaveBritneyAlone$2(EssentialsLoggingConfigurerTest.java:33)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.Iterator.forEachRemaining(Iterator.java:116)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at io.jenkins.plugins.essentials.logging.EssentialsLoggingConfigurerTest.leaveBritneyAlone(EssentialsLoggingConfigurerTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:548)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(FileInputStream.java:255)
at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
at java.io.InputStreamReader.read(InputStreamReader.java:184)
at java.io.BufferedReader.fill(BufferedReader.java:161)
at java.io.BufferedReader.readLine(BufferedReader.java:324)
at java.io.BufferedReader.readLine(BufferedReader.java:389)
at org.apache.commons.io.IOUtils.readLines(IOUtils.java:1030)
at org.apache.commons.io.IOUtils.readLines(IOUtils.java:987)
at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1784)
at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1819)
at io.jenkins.plugins.essentials.logging.EssentialsLoggingConfigurerTest.lambda$leaveBritneyAlone$2(EssentialsLoggingConfigurerTest.java:26)
... 24 more
Standard Output
=== Starting leaveBritneyAlone(io.jenkins.plugins.essentials.logging.EssentialsLoggingConfigurerTest)
Standard Error
0.015 [id=76]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:49266/jenkins/
0.091 [id=83]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
0.093 [id=94]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
0.171 [id=88]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
0.172 [id=88]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
0.173 [id=88]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
0.174 [id=88]	SEVERE	i.j.p.e.l.EssentialsLoggingConfigurer#configure: I started!
0.175 [id=88]	INFO	i.j.p.e.l.EssentialsLoggingConfigurer#checkNotTooManyLogsAlready: There are 0 log entries that were generated already.
0.629 [id=84]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
0.710 [id=82]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
0.934 [id=76]	INFO	jenkins.model.Jenkins#cleanUp: Stopping Jenkins
1.007 [id=76]	INFO	jenkins.model.Jenkins#cleanUp: Jenkins stopped
java.io.IOException: Failed to clean up temp dirs
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.dispose(TemporaryDirectoryAllocator.java:87)
at org.jvnet.hudson.test.TestEnvironment.dispose(TestEnvironment.java:84)
at org.jvnet.hudson.test.JenkinsRule.after(JenkinsRule.java:499)
at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:564)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unable to delete 'C:\Windows\TEMP\jenkinsTests.tmp\jenkins238635660406051271test\logs\essentials.log.0'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
at hudson.Util.deleteFile(Util.java:274)
at hudson.FilePath.deleteRecursive(FilePath.java:1232)
at hudson.FilePath.deleteContentsRecursive(FilePath.java:1241)
at hudson.FilePath.deleteRecursive(FilePath.java:1223)
at hudson.FilePath.deleteContentsRecursive(FilePath.java:1241)
at hudson.FilePath.deleteRecursive(FilePath.java:1223)
at hudson.FilePath.access$1200(FilePath.java:208)
at hudson.FilePath$DeleteRecursive.invoke(FilePath.java:1203)
at hudson.FilePath$DeleteRecursive.invoke(FilePath.java:1199)
at hudson.FilePath.act(FilePath.java:1009)
at hudson.FilePath.act(FilePath.java:987)
at hudson.FilePath.deleteRecursive(FilePath.java:1197)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.dispose(TemporaryDirectoryAllocator.java:82)
... 7 more
Caused by: java.nio.file.FileSystemException: C:\Windows\TEMP\jenkinsTests.tmp\jenkins238635660406051271test\logs\essentials.log.0: The process cannot access the file because it is being used by another process.
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
at java.nio.file.Files.deleteIfExists(Files.java:1165)
at hudson.Util.tryOnceDeleteFile(Util.java:313)
at hudson.Util.deleteFile(Util.java:269)
... 19 more
```